export const programs: string[] = [
  '3D Computer Animation',
  'Academic Upgrading',
  'Administrative Business Management',
  'Advanced Building Systems',
  'Advanced CNC Manufacturing',
  'Advanced Police Studies',
  'Advertising and Marketing Communications',
  'Animation',
  'Applied Artificial Intelligence & Machine Learning (Optional Co-op)',
  'Applied Electrical Motion and Control Management',
  'Applied Electrical Motion and Control Management - Automotive',
  'Applied Electrical Motion and Control Management - Logistical Automation',
  'Applied Energy Management',
  'Applied Energy Management - Energy Systems Control',
  'Applied Energy Management - Renewable Energy Stream',
  'Applied Energy Management - Residential and Commercial',
  'Applied Manufacturing Management - Automation Stream (formerly Applied Manufacturing Management - Mechatronics Stream)',
  'Applied Manufacturing Management - Design Integration (Aerospace Stream)',
  'Applied Manufacturing Management - Design Integration 3D Printing Stream',
  'Applied Manufacturing Management - Design Integration Stream',
  'Applied Manufacturing Management - Machining Stream',
  'Applied Manufacturing Management - Welding Stream',
  'Applied Manufacturing Management - Welding Stream (2022-2023)',
  'Applied Network Infrastructure and System Administration',
  'Applied Research (Optional Co-op)',
  'Architecture - Construction Engineering Technology (Optional Co-op)',
  'Autism and Behavioural Science',
  'Aviation - General Arts and Science',
  'Aviation - General Arts and Science Fast Track',
  'Bachelor of Applied Biotechnology (Honours)',
  'Bachelor of Applied Health Information Science (Honours)',
  'Bachelor of Applied Technology (Honours) - Architecture - Project and Facility Management',
  'Bachelor of Business Administration (Honours) - Accounting, Audit and Information Technology',
  'Bachelor of Business Administration (Honours) - International Business Management',
  'Bachelor of Commerce (Honours) - Financial Services',
  'Bachelor of Communications Management (Honours)',
  'Bachelor of Community and Criminal Justice (Honours)',
  'Bachelor of Computer Science (Honours)',
  'Bachelor of Design (Honours)',
  'Bachelor of Early Learning Program Development (Honours)',
  'Bachelor of Engineering - Building Systems Engineering',
  'Bachelor of Engineering - Cyber Systems Engineering',
  'Bachelor of Engineering - Electronic Systems Engineering',
  'Bachelor of Engineering - Mechanical Systems Engineering',
  'Bachelor of Engineering - Power Systems Engineering',
  'Bachelor of Environmental Public Health (Honours)',
  'Bachelor of Interior Design (Honours)',
  'Bachelor of Public Relations (Honours)',
  'Baking and Pastry Arts',
  'Baking and Pastry Arts Management (Optional Co-op)',
  'Bartending',
  'Big Data Solution Architecture (Optional Co-op)',
  'Biotechnology Technician',
  'Biotechnology Technician Fast Track',
  'Bookkeeping',
  'Broadcast - Radio',
  'Broadcasting - Television and Independent Production',
  'Broadcasting Performance and Digital Media',
  'Building Superintendence and Repair',
  'Business',
  'Business - Finance',
  'Business - Insurance (Optional Co-op)',
  'Business - International Business',
  'Business - Marketing',
  'Business - Marketing - Accelerated',
  'Business - Purchasing',
  'Business - Supply Chain and Operations for Commercial Trucking',
  'Business Administration - Accounting',
  'Business Administration - Accounting Accelerated',
  'Business Administration - Financial Planning',
  'Business Administration - Management',
  'Business Administration - Marketing',
  'Business Administration - Marketing (Co-op)',
  'Business Administration - Supply Chain and Operations Management',
  'Business Administration - Supply Chain and Operations Management (Co-op)',
  'Business Analytics',
  'Business Development and Sales',
  'Business Fundamentals',
  'Business Management - Entrepreneurship and Innovation',
  'Career Development Professional',
  'Carpentry and Renovation Technician (Optional Co-op)',
  'Civil Engineering Technology (Optional Co-op)',
  'Cloud Data Management',
  'Community Integration Through Co-operative Education',
  'Computer Animation - Motion Graphics',
  'Computer Application Security (Optional Co-op)',
  'Computer Applications Development (Optional Co-op)',
  'Computer Engineering Technology (Optional Co-op)',
  'Computer Programming',
  'Computer Programming and Analysis (Optional Co-op)',
  'Computer Systems Technician - Information Technology Infrastructure and Services (Optional Co-op)',
  'Computer-Aided Drafting and Design',
  'Construction Foundations',
  'Construction Management (Optional Co-op)',
  'Construction Project Management',
  'Construction Techniques - Brick and Stone',
  'Construction Techniques (Carpentry)',
  'Construction Techniques (Carpentry, Electrical, HVAC and Welding)',
  'Construction Techniques (Masonry, Plumbing, Electrical, and Carpentry)',
  'Construction Techniques (Welding, HVAC, Plumbing, and Masonry)',
  'Culinary Management (Co-op)',
  'Culinary Skills (Co-op)',
  'Data Processing and Reporting',
  'Design Foundations',
  'Digital Solutions Management (Optional Co-op)',
  'Diploma Registered Practical Nurse to B.Sc.N. (McMaster)',
  'Drafting and Design for Additive Manufacturing',
  'Early Childhood Education',
  'Early Childhood Education Fast Track (ECE)',
  'Early Childhood Education Fast Track (ECE) (International)',
  'Early Childhood Education Resource Consulting',
  'Early Childhood Education Resource Consulting International',
  'Educational Support',
  'Electrical Engineering Technician',
  'Electrical Engineering Technology (Optional Co-op)',
  'Electrical Technician - Industrial (Optional Co-op)',
  'Electrical Techniques',
  'Electro Mechanical and Automation Maintenance (Optional Co-op)',
  'Electronics Engineering Technician',
  'Electronics Engineering Technology (Optional Co-op)',
  'Embedded Systems Development (Optional Co-op)',
  'Energy Systems Engineering Technology - Electrical (Optional Co-op)',
  'English for Academic Studies',
  'Enhanced Practice for Internationally Educated Nurses',
  'Environmental Building Sciences',
  'Environmental Engineering Applications (Optional Co-op)',
  'Esports Marketing and Event Management',
  'Esthetician',
  'Event Management',
  'Financial Planning Services',
  'Financial Technology',
  'Fitness and Health Promotion',
  'Food and Beverage Management - Hotel and Restaurant Operations (Optional Co-op)',
  'Food Processing Technician (Optional Co-op)',
  'Food Safety and Quality Assurance - Food Processing',
  'Food Service Worker',
  'Game - Design',
  'General Arts and Science - Diploma Option',
  'General Arts and Science - One Year',
  'General Arts and Science: English Language Studies',
  'Global Business Management',
  'Global Hospitality Management (Optional Co-op)',
  'Graphic Design',
  'Health and Social Systems Navigation',
  'Health Care Administration and Service Management (2023)',
  'Health Care Administration Management (Nursing Leadership Stream)',
  'Health Office Administration',
  'Hearing Instrument Specialist',
  'Heating, Refrigeration and Air Conditioning Technician',
  'Heavy Construction Equipment Operation',
  'Hospitality Operations - Food and Beverage',
  'Human Factors and Ergonomics',
  'Human Resources Management (Optional Co-op)',
  'Human Services Foundation',
  'Information Technology Business Analysis',
  'Information Technology Infrastructure',
  'Information Technology Network Security',
  'Information Technology Project Management',
  'Interactive Media Management - Interaction Design',
  'Interior Decorating',
  'IT Innovation and Design (Optional Co-op)',
  'Journalism',
  'Language Instruction for Newcomers to Canada (LINC)',
  'Machining for Manufacturing',
  'Management and Leadership Development',
  'Management in Community Services (Formerly: Community and Social Services Management)',
  'Manufacturing Engineering Technology - Welding and Robotics (Optional Co-op)',
  'Massage Therapy',
  'Mechanical Engineering Technician - Automated Manufacturing (Optional Co-op)',
  'Mechanical Engineering Technology - Automated Manufacturing (Optional Co-op)',
  'Mechanical Technician - CNC',
  'Mechanical Technician - General Machinist (Optional Co-op)',
  'Mechanical Technician - Tool and Die/Tool Maker (Optional Co-op)',
  'Mechanical Techniques - Gas and Sheet Metal',
  'Mechanical Techniques - Industrial Millwright',
  'Mechanical Techniques - Plumbing',
  'Mechanical Techniques - Precision Machining and Tooling',
  'Media Foundations',
  'Medical Laboratory Science',
  'Medical Office Practices',
  'Mental Health and Substance Use',
  'Mobile Solutions Development (Optional Co-op)',
  'Motive Power Fundamentals - Automotive Repair',
  'Motive Power Technician - Automotive Service',
  'Motive Power Technician - Heavy Duty Equipment (Optional Co-op)',
  'Motive Power Technician - Truck and Coach',
  'Motive Power Techniques - Heavy Duty Equipment Repair',
  'Motive Power Techniques - Truck and Coach Repair',
  'Network Technical Support',
  'Nursing - BScN (McMaster)',
  'Nutrition and Food Service Management',
  'Occupation Specific Language Training (OSLT)',
  'Occupational Health, Safety and Wellness',
  'Occupational Therapist Assistant & Physiotherapist Assistant',
  'Office Administration - Executive',
  'Office Administration - General',
  'Office Administration - Legal',
  'Operations Leadership in Food Manufacturing',
  'Packaging Engineering Technician (Optional Co-op)',
  'Paramedic',
  'Payroll and Bookkeeping (Optional Co-op)',
  'Personal Support Worker',
  'Personal Support Worker - FAST Delivery',
  'Personal Support Worker - International',
  'Police Foundations',
  'Power Engineering Techniques - 3rd Class',
  'Power Engineering Techniques - 4th Class',
  'Power Engineering Technology',
  'Powerline Technician (Optional Co-op)',
  'Practical Nursing',
  'Pre-Apprenticeship General Carpenter',
  'Pre-Apprenticeship Introduction to Construction Trades',
  'Pre-Apprenticeship Welder/Metal Fabricator',
  'Predictive Analytics',
  'Pre-Health Sciences Pathway to Advanced Diplomas and Degrees',
  'Pre-Health Sciences Pathway to Certificates and Diplomas',
  'Pre-Service Firefighter Education and Training',
  'Process Quality Engineering',
  'Production GMAW Welder',
  'Professional Accounting Practice',
  'Professional Cheese Making',
  'Project Management',
  'Protection, Security and Investigation',
  'Public Relations',
  'Public Relations - Integrated Communications (Optional Co-op)',
  'Public Service (Optional Co-op)',
  'Quality Assurance - Manufacturing and Management',
  'Reception and Customer Service',
  'Recreation and Leisure Services',
  'Regulatory Affairs',
  'Renewable Energy Techniques',
  'Reporting Systems and Database Development',
  'Respiratory Therapy',
  'Robotics and Industrial Automation (Optional Co-op)',
  'Sensory Loss Intervention',
  'Social Media Marketing',
  'Social Service Worker',
  'Software Engineering Technician',
  'Software Engineering Technology (Optional Co-op)',
  'Software Quality Assurance and Test Engineering (Optional Co-op)',
  'Strategic Global Business Management',
  'Strategic Marketing Communications',
  'Structural Packaging Design and Management',
  'Structural Steel Management and Detailing (Optional Co-op)',
  'Supply Chain Management - Global',
  'Supportive Care',
  'Sustainable Business Management (Optional Co-op)',
  'Teaching English as a Second Language',
  'Technical Communication (Optional Co-op)',
  'Technology Foundations',
  'Tourism - Destinations and Travel Management (Optional Co-op)',
  'Virtual Reality Production',
  'Virtualization and Cloud Computing',
  'Visual Merchandising Arts',
  'Web Development',
  'Web Development and Internet Applications Fundamentals',
  'Welding and Fabrication Technician',
  'Welding Engineering Technician - Robotics (Optional Co-op)',
  'Welding Engineering Technology - Inspection (Optional Co-op)',
  'Welding Techniques',
  'Wireless Network Infrastructure',
  'Women in Skilled Trades (WIST) General Carpenter Pre-Apprenticeship',
  'Woodworking Technician',
  'Woodworking Techniques - CNC',
  'Woodworking Technology (Optional Co-op)'
]
