import '../../dist/output.css'
import type { AppProps } from 'next/app'
import { AppLayout } from 'components/Utils/AppLayout'
import { AuthUserProvider } from 'context/authUserContext'
import Head from 'next/head'

export default function App ({ Component, pageProps }: AppProps) {
  return (
    <AppLayout>
      <AuthUserProvider>
        <Head>
          <title>Connet | Conestoga Network</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="logo_ico.ico" />
        </Head>
        <Component {...pageProps}/>
      </AuthUserProvider>
    </AppLayout>
  )
}
