import { auth, logoutWithEmail } from '@firebase/client'
import { Card } from 'flowbite-react'
import Head from 'next/head'
import { useAuthState } from 'react-firebase-hooks/auth'

export default function Home () {
  const [user, loading, error] = useAuthState(auth)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen'>
        <Card href='#'>
          <h1>Hola</h1>
          <button onClick={logoutWithEmail}>Logout</button>
        </Card>
      </main>
    </>
  )
}
